#name: Run tests

#on:
#  workflow_dispatch:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

#permissions:
#  checks: write

#jobs:
#  launch-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-java@v2
#        with:
 #         java-version: 17
#          cache: 'gradle'
 # #        distribution: 'zulu'
 #     - name: Setup Gradle
 #       uses: gradle/actions/setup-gradle@v3
 #     - name: Grant execute permission for gradlew
 #       run: chmod +x gradlew
 #     - name: Run unit tests
 #       run: ./gradlew testDebugUnitTest
 #     - name: Test Report
 #       uses: dorny/test-reporter@v1
 #       if: success() || failure()    # run this step even if previous step failed
 #       with:
 #         name: tests-report            # Name of the check run which will be created
 #         path: app/build/test-results/testDebugUnitTest/TEST-*.xml    # Path to test results
 #         reporter: java-junit        # Format of test results